name: CI/CD
on:
  push:
    branches:
      - feature/*
      - master
    paths:
      - 'src/**'

  workflow_dispatch:
  
jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    with: 
      project-name: ${{ vars.PROJECT_NAME }}
    secrets:
      gha-token: ${{ secrets.MY_GITHUB_ACTIONS_PAT_PACKAGE_FEED }}
