name: CI/CD > CI
on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
    secrets:
      gha-token:
        description: GitHub Actions access token
        required: true
    outputs:
      tag:
        value: ${{ jobs.ci.outputs.new_tag }}
      version:
        value: ${{ jobs.ci.outputs.new_version }}
  
jobs:
  ci:
    name: Build and Test
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
      new_version: ${{ steps.tag_version.outputs.new_version }}    
    steps:
      - name: Check-out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore NuGet packages dependencies
        run: |
          dotnet restore src/MySample.csproj

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pre_release_branches: ${{ vars.VERSION_PRERELEASE_BRANCHES }}
          release_branches: ${{ vars.VERSION_RELEASE_BRANCHES }}
          tag_prefix: 'TerranProject.samples-v'
          append_to_pre_release_tag: 'prerelease'
