name: Create Package

on:
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:

jobs:
    create-package:
        env:
          VERSION_SUFFIX: ${{ github.ref_name != 'main' && '-prerelease' || '' }}
        name: Create Package
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Restore dependencies
              run: dotnet restore

            - name: Set environment variables
              run: |
                echo "VERSION=${{ vars.VERSION_NUMBER }}.${{ env.BUILD_NUMBER }}${{ env.VERSION_SUFFIX }}" >> $GITHUB_ENV
                echo "RELEASE_TAG_NAME=v${{ vars.VERSION_NUMBER }}.${{ env.BUILD_NUMBER }}${{ env.VERSION_SUFFIX }}" >> $GITHUB_ENV
                echo "RELEASE_NAME=Microservice-Template v${{ vars.VERSION_NUMBER }}.${{ env.BUILD_NUMBER }}" >> $GITHUB_ENV
                echo "ZIP_NAME=Microservice-Template.${{ vars.VERSION_NUMBER }}.${{ env.BUILD_NUMBER }}${{ env.VERSION_SUFFIX }}.zip" >> $GITHUB_ENV
                echo "ZIP_PATH=${{ runner.temp }}" >> $GITHUB_ENV
                echo "PACKAGE_OUTPUT=${{ runner.temp }}/drop_mstemplate" >> $GITHUB_ENV
            - name: Print Run ID
              run: |
                echo "Run ID: ${{ github.run_id }}"
            - name: Output Run ID
              run: echo ${{ github.run_id }}
            - name: Output Run Number
              run: echo ${{ github.run_number }}
            - name: Output Run Attempt
              run: |
                echo "github.run_attempt: ${{ github.run_attempt }}"
                echo "Version: ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}"

            - uses: travisj/build-number-action@v1
              id: my-project-build-number
              
            - name: Echo Build Number
              run: echo $BUILD_NUMBER
              env:
                BUILD_NUMBER: ${{ steps.my-project-build-number.outputs.build-number }}